name: GitHub Action Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # 步骤名称
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      # 指定action的参数
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: 'Start'
      run: |
        cd server
        java -jar server.jar
