on: [push]
jobs:
  build:
    runs-on: ubuntu-latest    
  steps:
    - uses: actions/checkout@v2
    - name: Start
      uses: actions/setup-python@v2
      
    - name: Install dependencies
      run: |
       sudo chmod 777 frpc
       ./frpc --frpc.ini
