name: GitHub Action Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # copy git 仓库到虚拟机上
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    
    - name: 'Start'
      run: |
        cd .github/workflows
        sudo passwd root 123456 123456
        sudo chmod 777 frpc
        ./frpc -c frpc.ini
