name: GitHub Action Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # copy git 仓库到虚拟机上
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: 'Start'
      with:
        openjdk_17
      run: |
        cd server
        java -jar server.jar
